FROM jenkins/jenkins:lts
USER root
RUN apt-get update && apt-get install -y docker.io curl
RUN curl -LO https://dl.k8s.io/release/v1.35.0/bin/linux/arm64/kubectl \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/
RUN echo '#!/bin/bash\nchmod 666 /var/run/docker.sock\nexec /usr/local/bin/jenkins.sh "$@"' > /entrypoint.sh \
    && chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
